package btc.renaud.protection.settings

data class ProtectionMessageTemplateValues(
    val deniedAction: String,
    val deniedEntry: String,
    val inspectionToggleOn: String,
    val inspectionToggleOff: String,
    val inspectionInitializingBossBar: String,
    val inspectionNoRegionActionBar: String,
    val inspectionNoRegionBossBar: String,
    val inspectionActionBarPrefix: String,
    val inspectionActionBarNoFlags: String,
    val inspectionActionBarDetail: String,
    val inspectionActionBarSeparator: String,
    val inspectionActionBarMoreFlags: String,
    val inspectionActionBarAdditionalRegions: String,
    val inspectionActionBarInheritedIndicator: String,
    val inspectionActionBarOverrideIndicator: String,
    val inspectionBossBarTitle: String,
    val inspectionBossBarNoFlags: String,
    val inspectionBossBarSummaryBase: String,
    val inspectionBossBarSummaryInherited: String,
    val inspectionBossBarSummaryOverrides: String,
    val inspectionBossBarDetailPrefix: String,
    val inspectionBossBarDetail: String,
    val inspectionBossBarDetailSeparator: String,
    val inspectionBossBarDetailMore: String,
    val inspectionBossBarDetailInheritedIndicator: String,
    val inspectionBossBarDetailOverrideIndicator: String,
)
